# Generated by Django 3.2 on 2022-06-23 10:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('source_id', models.CharField(max_length=30)),
                ('source_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=10000)),
                ('url', models.CharField(max_length=300)),
                ('image', models.CharField(max_length=100)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('content', models.TextField(max_length=10000)),
                ('news_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.source')),
            ],
        ),
    ]
